<?php

namespace DoctrineORMModule\Proxy\__CG__\SourceCode\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnalysisResults extends \SourceCode\Model\Entity\AnalysisResults implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }



    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'id', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'sourceCode', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberUsefulLines', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberVariables', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberLogicalConnectives', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberDiversionCommands', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberRegionsGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberEdgesGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberVertexGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'cyclomaticComplexity', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'graph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'arithmeticMean'];
        }

        return ['__isInitialized__', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'id', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'sourceCode', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberUsefulLines', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberVariables', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberLogicalConnectives', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberDiversionCommands', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberRegionsGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberEdgesGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'numberVertexGraph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'cyclomaticComplexity', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'graph', '' . "\0" . 'SourceCode\\Model\\Entity\\AnalysisResults' . "\0" . 'arithmeticMean'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AnalysisResults $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceCode', []);

        return parent::getSourceCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourceCode($sourceCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourceCode', [$sourceCode]);

        return parent::setSourceCode($sourceCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberUsefulLines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberUsefulLines', []);

        return parent::getNumberUsefulLines();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberUsefulLines($numberUsefulLines)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberUsefulLines', [$numberUsefulLines]);

        return parent::setNumberUsefulLines($numberUsefulLines);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberVariables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberVariables', []);

        return parent::getNumberVariables();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberVariables($numberVariables)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberVariables', [$numberVariables]);

        return parent::setNumberVariables($numberVariables);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberLogicalConnectives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberLogicalConnectives', []);

        return parent::getNumberLogicalConnectives();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberLogicalConnectives($numberLogicalConnectives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberLogicalConnectives', [$numberLogicalConnectives]);

        return parent::setNumberLogicalConnectives($numberLogicalConnectives);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberDiversionCommands()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberDiversionCommands', []);

        return parent::getNumberDiversionCommands();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberDiversionCommands($numberDiversionCommands)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberDiversionCommands', [$numberDiversionCommands]);

        return parent::setNumberDiversionCommands($numberDiversionCommands);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberRegionsGraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberRegionsGraph', []);

        return parent::getNumberRegionsGraph();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberRegionsGraph($numberRegionsGraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberRegionsGraph', [$numberRegionsGraph]);

        return parent::setNumberRegionsGraph($numberRegionsGraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberEdgesGraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberEdgesGraph', []);

        return parent::getNumberEdgesGraph();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberEdgesGraph($numberEdgesGraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberEdgesGraph', [$numberEdgesGraph]);

        return parent::setNumberEdgesGraph($numberEdgesGraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberVertexGraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberVertexGraph', []);

        return parent::getNumberVertexGraph();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberVertexGraph($numberVertexGraph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberVertexGraph', [$numberVertexGraph]);

        return parent::setNumberVertexGraph($numberVertexGraph);
    }

    /**
     * {@inheritDoc}
     */
    public function getCyclomaticComplexity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCyclomaticComplexity', []);

        return parent::getCyclomaticComplexity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCyclomaticComplexity($cyclomaticComplexity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCyclomaticComplexity', [$cyclomaticComplexity]);

        return parent::setCyclomaticComplexity($cyclomaticComplexity);
    }

    /**
     * {@inheritDoc}
     */
    public function getGraph()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGraph', []);

        return parent::getGraph();
    }

    /**
     * {@inheritDoc}
     */
    public function setGraph($graph)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGraph', [$graph]);

        return parent::setGraph($graph);
    }

    /**
     * {@inheritDoc}
     */
    public function getArithmeticMean()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArithmeticMean', []);

        return parent::getArithmeticMean();
    }

    /**
     * {@inheritDoc}
     */
    public function setArithmeticMean()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArithmeticMean', []);

        return parent::setArithmeticMean();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData(\Doctrine\ORM\EntityManager $em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', [$em]);

        return parent::getData($em);
    }

}
