<?php

namespace DoctrineORMModule\Proxy\__CG__\SourceCode\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SourceCode extends \SourceCode\Model\Entity\SourceCode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }



    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'id', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'content', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'submissionDate', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'problem', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'language', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'user', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'analysisResults', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'ranking'];
        }

        return ['__isInitialized__', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'id', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'content', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'submissionDate', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'problem', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'language', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'user', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'analysisResults', '' . "\0" . 'SourceCode\\Model\\Entity\\SourceCode' . "\0" . 'ranking'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SourceCode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubmissionDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubmissionDate', []);

        return parent::getSubmissionDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubmissionDate($submissionDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubmissionDate', [$submissionDate]);

        return parent::setSubmissionDate($submissionDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblem', []);

        return parent::getProblem();
    }

    /**
     * {@inheritDoc}
     */
    public function setProblem($problem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProblem', [$problem]);

        return parent::setProblem($problem);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage($language)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalysisResults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalysisResults', []);

        return parent::getAnalysisResults();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalysisResults($analysisResults)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalysisResults', [$analysisResults]);

        return parent::setAnalysisResults($analysisResults);
    }

    /**
     * {@inheritDoc}
     */
    public function getRanking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRanking', []);

        return parent::getRanking();
    }

    /**
     * {@inheritDoc}
     */
    public function setRanking($ranking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRanking', [$ranking]);

        return parent::setRanking($ranking);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

}
