<div class="col-md-12 p-t-5 p-r-4 p-l-4">
    <style>
        .side-navbar ul.list-unstyled li:nth-child(2) a {
            background: #eef5f9;
        }
    </style>
    <div class="card form">
        <div class="card-header align-items-center">
            <h3 class="text-center">TITULO DO PROBLEMA</h3>
            <h5 class="text-center text-blue font-weight-normal"> CATEGORIA DO PROBLEMA</h5>
        </div>
        <div class="card-body">
            <form id="submission-form">
                <div class="form-group row p-t-0 p-b-0 p-l-0 p-r-0">
                    <div class="form-group col-md-12 p-l-0">
                        <label for="source-code" class="form-control-label">Insira sua solução</label>
                        <textarea id="source-code" type="text" rows="50" required=""  class="lined" cols="110"></textarea>
                    </div>
                </div>
            </form>
            <div class="form-group">
                <button class="btn btn-success pull-right" ng-click=""><i class="fa fa-upload" aria-hidden="true"></i> Enviar Solução</button>
            </div>
        </div>
    </div>
</div>