<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Sistema\Controller\SistemaController' => __DIR__ . '/src/Sistema/Controller/SistemaController.php',
  'Sistema\Controller\AuthController' => __DIR__ . '/src/Sistema/Controller/AuthController.php',
  'Sistema\Module'                               => __DIR__ . '/Module.php',
);
