<div class="form d-flex align-items-center">
    <div class="content">
        <?php if($result != null) { ?>
            <div class="alert alert-danger alert-dismissible m-b-5" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong><?php echo $result ?></strong>
            </div>
        <?php } ?>
        <form id="login-form" method="post" action="/login">
            <div class="form-group">
                <input id="login-username" type="text" name="email" required="" class="input-material">
                <label for="login-username" class="label-material">E-mail</label>
            </div>
            <div class="form-group">
                <input id="login-password" type="password" name="password" required="" class="input-material">
                <label for="login-password" class="label-material">Senha</label>
            </div>
            <button id="login" type="submit" class="btn btn-primary">Login</button>
        </form><a href="/recover-password" class="forgot-pass">Esqueceu a senha?</a><br><small>Não possui uma conta? </small><a href="/register" class="signup">Cadastre-se</a>
    </div>
</div>
