<div class="form d-flex align-items-center">
    <div class="content">
        <?php if($error != null) { ?>
            <div class="alert alert-danger alert-dismissible m-b-5" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong><?php echo $error ?></strong>
            </div>
        <?php } ?>
        <form id="login-form" method="post">
            <div class="form-group">
                <input id="login-username" type="text" name="loginUsername" required="" class="input-material">
                <label for="login-username" class="label-material">E-mail</label>
            </div>
            <div class="form-group">
                <input id="login-password" type="password" name="loginPassword" required="" class="input-material">
                <label for="login-password" class="label-material">Senha</label>
            </div>
            <a id="login" href="index.html" class="btn btn-primary">Login</a>
        </form><a href="/recover-password" class="forgot-pass">Esqueceu a senha?</a><br><small>Não possui uma conta? </small><a href="/register" class="signup">Cadastre-se</a>
    </div>
</div>
