<div class="form d-flex align-items-center" ng-controller="AuthController">
    <div class="content">
        <div class="alert alert-dismissible m-b-5" role="alert" ng-class="{'alert-danger': recoverPassword.result.error != null, 'alert-info': recoverPassword.result.success != null}" ng-if="recoverPassword.result.success != null || recoverPassword.result.error != null">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <span ng-if="recoverPassword.result.success != null"><strong>{{recoverPassword.result.success != null}}</strong></span>
            <span ng-if="recoverPassword.result.error != null"><strong>{{recoverPassword.result.error != null}}</strong></span>
        </div>
        <form id="register-form">
            <div class="form-group">
                <input id="register-email" type="email" name="email" required class="input-material" ng-model="recoverPassword.model.email"/>
                <label for="register-email" class="label-material">E-mail</label>
            </div>
            <button id="register" class="btn btn-primary" ng-click="recoverPasswordAction()">Enviar</button>
        </form>
        <small>Retornar para o </small><a href="/login" class="signup">Login</a>
    </div>
</div>