<div class="form d-flex align-items-center">
    <div class="content">
        <form id="register-form">
            <div class="form-group">
                <input id="register-username" type="text" name="registerUsername" required class="input-material">
                <label for="register-username" class="label-material">Nome</label>
            </div>
            <!-- editar os tipos destes inputs -->
            <div class="form-group">
                <input id="register-birthday" type="text" name="register-birthday" required class="input-material">
                <label for="register-birthday" class="label-material">Data de nascimento</label>
            </div>
            <div class="form-group">
                <input id="register-school" type="text" name="register-school" required class="input-material">
                <label for="register-school" class="label-material">Curso</label>
            </div>
            <div class="form-group"> <!-- colocar checkbox -->
                <input id="register-gender" type="text" name="register-gender" required class="input-material">
                <label for="register-gender" class="label-material">Gênero</label>
            </div>
            <div class="form-group">
                <input id="register-email" type="email" name="registerEmail" required class="input-material">
                <label for="register-email" class="label-material">E-mail</label>
            </div>
            <div class="form-group">
                <input id="register-passowrd" type="password" name="registerPassword" required class="input-material">
                <label for="register-passowrd" class="label-material">Senha</label>
            </div>
            <div class="form-group terms-conditions">
                <input id="license" type="checkbox" class="checkbox-template">
                <label for="license">Agree the terms and policy</label>
            </div>
            <input id="register" type="submit" value="Cadastrar" class="btn btn-primary">
        </form><small>Já possui uma conta? </small><a href="/login" class="signup">Login</a>
    </div>
</div>