<?php
/**
 * TCC - Ciência da Computação, URI Santo Ângelo
 * Orientador: Denílson Rodrigues da Silva <deniro@san.uri.br>
 * @author Karla dos Santos Lencina <karla.krs@outlook.com>
 * 404 NOT FOUND
 *
 */
namespace Application;?>

<style>
    .p {
        /* 	width: 10%; */
        height: 100%;
        color: #ff9eb9;
        /* 	background: red; */
        font-size: 200px;
        display: inline-block;
        font-family: 'Anton', sans-serif;
    }
    .error {
        margin-bottom: 100px !important;
    }
</style>
<div class="container">
    <div  class="error text-center">
        <p class="p">4</p>
        <img src="<?=$this->basePath()?>/img/404.png" width="25%"/>
        <p class="p">4</p>

        <div class="page-ms">
            <p class="page-msg"> Ops, página não encontrada!</p>
            <a href="/home" class="btn-success btn">Voltar</a>
        </div>
    </div>
    <!-- 	<p>Auto back to home page</p> -->
</div>