<?= $this->doctype() ?>

<html lang="en" ng-app="app">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('TCC')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
//            ->prependStylesheet($this->basePath('css/style.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
//            ->prependFile($this->basePath('js/bootstrap.min.js'))
//            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="all,follow">
        <!-- Bootstrap CSS-->
        <link rel="stylesheet" href="<?=$this->basePath()?>/plugins/bootstrap/css/bootstrap.css">
        <!-- Google fonts - Roboto -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
        <!-- CSS Stylesheet -->
        <link rel="stylesheet" href="<?=$this->basePath()?>/css/minify/all.min.css" id="theme-stylesheet">
        <link rel="stylesheet" href="<?=$this->basePath()?>/plugins/test/jquery-linedtextarea.css" id="theme-stylesheet">
        <!-- CSS SweetAlert -->
        <link rel="stylesheet" href="<?=$this->basePath()?>/css/sweetalert/import/sweetalert.css" id="theme-stylesheet">
        <!-- Font Awesome CDN-->
        <link rel="stylesheet" href="<?=$this->basePath()?>/plugins/font-awesome/css/font-awesome.css">

        <!-- Tweaks for older IEs--><!--[if lt IE 9] -->
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="<?=$this->basePath()?>/js/app/minify/all.min.js"></script>
    <script src="<?=$this->basePath()?>/js/app/minify/cytoscape.min.js"></script>
    <script src="<?=$this->basePath()?>/node_modules/"></script>
    </head>
    <body>
        <div class="page home-page">
            <!-- Main Navbar-->
            <header class="header">
                <nav class="navbar">
                    <!-- Search Box-->
                    <div class="search-box">
                        <button class="dismiss"><i class="icon-close"></i></button>
                        <form id="searchForm" action="#" role="search">
                            <input type="search" placeholder="What are you looking for..." class="form-control">
                        </form>
                    </div>
                    <div class="container-fluid">
                        <div class="navbar-holder d-flex align-items-center justify-content-between">
                            <!-- Navbar Header-->
                            <div class="navbar-header">
                                <!-- Navbar Brand --><a href="/home" class="navbar-brand">
                                    <div class="brand-text brand-big hidden-lg-down"><span>Nome </span><strong>Aplicação</strong></div>
                                    <div class="brand-text brand-small"><strong>NA</strong></div></a>
                                <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
                            </div>
                            <!-- Navbar Menu -->
                            <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                                <!-- Search-->
<!--                                <li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>-->
                                <!-- Notifications-->
<!--                                <li class="nav-item dropdown"> <a id="notifications" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-bell-o"></i><span class="badge bg-red">12</span></a>-->
<!--                                    <ul aria-labelledby="notifications" class="dropdown-menu">-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item">-->
<!--                                                <div class="notification">-->
<!--                                                    <div class="notification-content"><i class="fa fa-envelope bg-green"></i>You have 6 new messages </div>-->
<!--                                                    <div class="notification-time"><small>4 minutes ago</small></div>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item">-->
<!--                                                <div class="notification">-->
<!--                                                    <div class="notification-content"><i class="fa fa-twitter bg-blue"></i>You have 2 followers</div>-->
<!--                                                    <div class="notification-time"><small>4 minutes ago</small></div>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item">-->
<!--                                                <div class="notification">-->
<!--                                                    <div class="notification-content"><i class="fa fa-upload bg-orange"></i>Server Rebooted</div>-->
<!--                                                    <div class="notification-time"><small>4 minutes ago</small></div>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item">-->
<!--                                                <div class="notification">-->
<!--                                                    <div class="notification-content"><i class="fa fa-twitter bg-blue"></i>You have 2 followers</div>-->
<!--                                                    <div class="notification-time"><small>10 minutes ago</small></div>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong>view all notifications                                            </strong></a></li>-->
<!--                                    </ul>-->
<!--                                </li>-->
                                <!-- Messages                        -->
<!--                                <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope-o"></i><span class="badge bg-orange">10</span></a>-->
<!--                                    <ul aria-labelledby="notifications" class="dropdown-menu">-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item d-flex">-->
<!--                                                <div class="msg-profile"> <img src="/img/avatar-1.jpg" alt="..." class="img-fluid rounded-circle"></div>-->
<!--                                                <div class="msg-body">-->
<!--                                                    <h3 class="h5">Jason Doe</h3><span>Sent You Message</span>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item d-flex">-->
<!--                                                <div class="msg-profile"> <img src="/img/avatar-2.jpg" alt="..." class="img-fluid rounded-circle"></div>-->
<!--                                                <div class="msg-body">-->
<!--                                                    <h3 class="h5">Frank Williams</h3><span>Sent You Message</span>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item d-flex">-->
<!--                                                <div class="msg-profile"> <img src="/img/avatar-3.jpg" alt="..." class="img-fluid rounded-circle"></div>-->
<!--                                                <div class="msg-body">-->
<!--                                                    <h3 class="h5">Ashley Wood</h3><span>Sent You Message</span>-->
<!--                                                </div></a></li>-->
<!--                                        <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong>Read all messages    </strong></a></li>-->
<!--                                    </ul>-->
<!--                                </li>-->
                                <!-- Logout    -->
                                <li class="nav-item"><a href="/logout" class="nav-link logout">Logout<i class="fa fa-sign-out"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="page-content d-flex align-items-stretch">
                <!-- Side Navbar -->
                <nav class="side-navbar">
                    <!-- Sidebar Header-->
                    <div class="sidebar-header d-flex align-items-center">
                        <div class="avatar"><img src="<?=$this->basePath()?>/img/avatar.png" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title">
                            <h1 class="h4"><?php echo $this->identity()->getProfile()->getFullName(); ?></h1>
                            <?php if($this->identity()->getProfile()->getGender() == "Feminino") { ?>
                            <p>Aluna</p>
                            <?php } else {?>
                            <p>Aluno</p>
                            <?php } ?>
                        </div>
                    </div>
                    <ul class="list-unstyled">
                        <?php
                            $partial = ['layout/navigation.phtml', 'Application'];
                            $this->navigation('default')->menu()->setPartial($partial);
                            echo $this->navigation('default')->menu()->render();
                        ?>
                    </ul>
                </nav>
                <div class="content-inner">
                    <!-- Page Header-->
<!--                    <header class="page-header">-->
<!--                        <div class="container-fluid">-->
<!--                            <h2 class="no-margin-bottom">Dashboard</h2>-->
<!--                        </div>-->
<!--                    </header>-->
                    <!-- Dashboard Counts Section-->
<!--                    <section class="dashboard-counts no-padding-bottom">-->
<!--                        <div class="container-fluid">-->
                            <?= $this->content ?>
<!--                        </div>-->
<!--                    </section>-->

                    <!-- Page Footer-->
                    <footer class="main-footer">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-6">
                                    <p>&copy; <?= date('Y') ?>. <?= 'Todos os direitos reservados.' ?></p>
                                </div>
                                <div class="col-sm-6 text-right">
                                    <p><a href="http://srvapp2s.santoangelo.uri.br/sites/site_novo/" class="external">URI Campus Santo Ângelo</a></p>
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>
        </div>
        <!-- Javascript files-->
        <!-- This is what you need -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <script src="<?=$this->basePath()?>/plugins/test/jquery-linedtextarea.js"></script>
        <script src="<?=$this->basePath()?>/plugins/tether/tether.min.js"></script>
        <script src="<?=$this->basePath()?>/plugins/bootstrap/js/bootstrap.js"></script>
        <script src="<?=$this->basePath()?>/plugins/jquery/jquery.cookie.js"> </script>
        <script src="<?=$this->basePath()?>/plugins/jquery/jquery.validate.min.js"></script>
        <script src="<?=$this->basePath()?>/js/front.js"></script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID.-->
        <!---->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
                function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
                e=o.createElement(i);r=o.getElementsByTagName(i)[0];
                e.src='//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');

            $(function() {
                $(".lined").linedtextarea(
                    {selectedLine: 1}
                );
            });
        </script>
        <?= $this->inlineScript() ?>
    </body>
</html>
