<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2014 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Sistema\Controller;

use Zend\Config\Reader\Json;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\JsonModel;
use Zend\View\Model\ViewModel;
use Core\Controller\RestfulController;

class SistemaController extends RestfulController
{
    public function indexAction()
    {
        return new ViewModel();
    }

    /**
     * @return JsonModel
     */
    public function getList()
    {
        return new JsonModel(array('mensagem' => 'Nada a listar')); // TODO: Change the autogenerated stub
    }
}
