<div class="form d-flex align-items-center">
    <div class="content">
        <form id="register-form">
            <div class="form-group">
                <input id="register-email" type="email" name="registerEmail" required class="input-material">
                <label for="register-email" class="label-material">Email Address      </label>
            </div>
            <input id="register" type="submit" value="Send" class="btn btn-primary">
        </form><small>Already have an account? </small><a href="login.html" class="signup">Login</a>
    </div>
</div>