<?php /**
 * TCC - Ciência da Computação, URI Santo Ângelo
 * Orientador: Denílson Rodrigues da Silva <deniro@san.uri.br>
 * @author Karla dos Santos Lencina <karla.krs@outlook.com>
 * Interface inicial da aplicação, tela de Home
 */
namespace Application;?>
<div class="col-md-12 p-t-5 p-r-4 p-l-4">
    <div class="card form">
        <!-- Título do problema -->
        <div class="card-header align-items-center p-b-0 p-t-5">
            <div class="row">
                <div class="col-md-6"><h3>Bem Vindo!</h3></div>
            </div>
        </div>

        <!-- Content para visualização de resultados da análise -->
        <div class="card-body p-t-2">

        </div>
    </div>
</div>