<?php /**
 * TCC - Ciência da Computação, URI Santo Ângelo
 * Orientador: Denílson Rodrigues da Silva <deniro@san.uri.br>
 * @author Karla dos Santos Lencina <karla.krs@outlook.com>
 * Interface inicial da aplicação, tela de Home
 */
namespace Application;?>
<div class="col-md-12 p-t-5 p-r-4 p-l-4">
    <div class="card form">
        <!-- Título do problema -->
        <div class="card-header align-items-center p-b-0 p-t-5">
            <div class="row">
                <div class="col-md-6"><h3>Bem Vindo ao ThinkCode!</h3></div>
            </div>
        </div>

        <!-- Content para visualização de resultados da análise -->
        <div class="card-body p-t-2">
            <div class="row">
                <div class="col-md-12 m-t-10">
                    <p>Nosso propósito é fazer você pensar diante dos seus códigos.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>No menu <i class="fa fa-lightbulb-o" aria-hidden="true"></i> Problemas você encontra desafios a serem solucionados.</p>
                    <p>Selecione o problema que deseja solucionar e submeta seu código-fonte, em seguida selecione uma solução que deseja comparar. Após o envio seu código será analisado, você passará a ter uma colocação no ranking e os resultados obtidos nas análises serão apresentados para você. Observe que quanto menores os resultados mostrados na análise da solução, melhor será a sua colocação no ranking do problema. Cada solução conterá um grafo representativo, que poderá ser manipulado, arrastando componentes, aumentado seu zoom de visualização ou selecionando um componente específico. Não sabe o que é um grado? <a href="https://pt.wikipedia.org/wiki/Teoria_dos_grafos" title="Link Wikipédia sobre Grafos">Clique aqui.</a></p>
                    <p>Para entender como o grafo representa o código inserido, verifique a representação de cada comando da linguagem no grafo, nas imagens a seguir:</p>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Linguagem C:</strong></p>
                            <img src="<?=$this->basePath()?>/img/graphElement/notacao_comandos_C.png" width="98%"/>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Portugol</strong></p>
                            <img src="<?=$this->basePath()?>/img/graphElement/notacao_comandos_P.png" width="100%"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>