<div class="col-md-12 p-t-5 p-r-4 p-l-4" ng-controller="ProblemController">
    <style>
        .table thead th {
            text-align: justify;
        }
    </style>
    <div class="card form">
        <div class="card-header d-flex align-items-center">
            <h3><i class="fa fa-lightbulb-o m-r-5" aria-hidden="true"></i> Problemas</h3>
        </div>
        <div class="card-body">
            <table ng-table="problemsListTools.tableParams" class="table table-hover" show-filter="false">
                <tbody class="clickable" ng-repeat="problem in $data" ng-click="problemsListTools.changeSelection(problem);">
                    <tr ng-class="{'table-active': problem.$selected}">
                        <td width="5%">
                            <i class="fa fa-check text-success" aria-hidden="true" ng-if="problem.resolved" title="Enviado"></i>
                        </td>
                        <td data-title-text="'#'">
                            {{problem.id}}
                        </td>
                        <td title="'Título'" filter="{ title: 'text'}" sortable="'title'">
                            {{problem.title}}
                        </td>
                        <td title="'Categoria'" filter="{ title: 'text'}" sortable="'categoryName'">
                            {{problem.category.name}}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>