<div class="col-md-12 p-t-5 p-r-4 p-l-4" ng-controller="ProblemController" ng-init="problemSelectedTools.initData('<?=$id?>');">
    <style>
        .side-navbar ul.list-unstyled li:nth-child(2) a {
            background: #eef5f9;
        }
    </style>
    <div class="card form">
        <div class="card-header align-items-center">
            <h3 class="text-center"> {{problemSelectedTools.problem.title}} <i class="fa fa-check text-success" aria-hidden="true" ng-if="problemSelectedTools.problem.resolved"></i></h3>
            <h5 class="text-center text-blue font-weight-normal"> {{problemSelectedTools.problem.categoryName}}</h5>
        </div>
        <div class="card-body text-center">
            <p>{{problemSelectedTools.problem.description}}</p>
            <div class="form-group">
                <button class="btn btn-success pull-right" ng-click="problemSelectedTools.submitProblem()"><i class="fa fa-upload" aria-hidden="true"></i> Enviar Solução</button>
            </div>
        </div>
    </div>
</div>